package gui;

import cmd.obj.Conversation;
import cmd.obj.Message;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class ConversationW extends Window {

    private final int conversationId;

    /**
     * Creates new form ConversationW
     *
     * @param parent
     * @param conversationDetails
     */
    public ConversationW(Window parent, Conversation conversationDetails) {
        super(parent);
        initComponents();
        this.conversationId = conversationDetails.getConversationId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPs = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jParticipant = new javax.swing.JTextField();
        jAddP = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jM = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMs = new javax.swing.JTextArea();
        jSend = new javax.swing.JButton();
        jMessage = new javax.swing.JTextField();
        jSendF = new javax.swing.JButton();
        jGetF = new javax.swing.JButton();
        jFToken = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(jPs);

        jLabel1.setText("Participants");

        jAddP.setText("Add participants");
        jAddP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddPActionPerformed(evt);
            }
        });

        jLabel3.setText("Participant");

        javax.swing.GroupLayout jPLayout = new javax.swing.GroupLayout(jP);
        jP.setLayout(jPLayout);
        jPLayout.setHorizontalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPLayout.createSequentialGroup()
                            .addComponent(jSeparator1)
                            .addGap(108, 108, 108))
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jAddP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPLayout.setVerticalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAddP)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel2.setText("Messages");

        jMs.setColumns(20);
        jMs.setRows(5);
        jScrollPane2.setViewportView(jMs);

        jSend.setText("Send");
        jSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendActionPerformed(evt);
            }
        });

        jSendF.setText("Send File");
        jSendF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendFActionPerformed(evt);
            }
        });

        jGetF.setText("Get File");
        jGetF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetFActionPerformed(evt);
            }
        });

        jFToken.setText("<insert file token>");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jMLayout = new javax.swing.GroupLayout(jM);
        jM.setLayout(jMLayout);
        jMLayout.setHorizontalGroup(
            jMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jMLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jMLayout.createSequentialGroup()
                        .addComponent(jFToken, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGetF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSendF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMLayout.createSequentialGroup()
                        .addComponent(jMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSend)))
                .addContainerGap())
        );
        jMLayout.setVerticalGroup(
            jMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMLayout.createSequentialGroup()
                        .addGroup(jMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSendF)
                            .addComponent(jFToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMLayout.createSequentialGroup()
                        .addGroup(jMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jMLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jGetF))
                            .addComponent(jSeparator2))
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendActionPerformed
        Message m = new Message(this.conversationId, jMessage.getText());
        MainW mw = (MainW) this.parent;
        try {
            mw.sendMessage(this.conversationId, m);
        } catch (IOException ex) {
            Logger.getLogger(ConversationW.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jSendActionPerformed

    private void jAddPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddPActionPerformed
        MainW mw = (MainW) parent;
        try {
            List<String> np = new ArrayList<>();   //the new participants
            np.add(this.jParticipant.getText());
            np.addAll(mw.getSelectedFriends());
            mw.addParticipants(this.conversationId, np);
        } catch (IOException ex) {
            Logger.getLogger(ConversationW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAddPActionPerformed

    private void jSendFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendFActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Pick a file");
            fc.showOpenDialog(null);
            File f = fc.getSelectedFile();
            Path path = Paths.get(f.getAbsolutePath());
            byte[] content = Files.readAllBytes(path);
            Window.c.transferFile(this.conversationId, f, content);
        } catch (IOException ex) {
            //Logger.getLogger(ConversationW.class.getName()).log(Level.SEVERE, null, ex);
            //System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jSendFActionPerformed

    private void jGetFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGetFActionPerformed
        Window.c.getFile(jFToken.getText());
    }//GEN-LAST:event_jGetFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddP;
    private javax.swing.JTextField jFToken;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JButton jGetF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jM;
    private javax.swing.JTextField jMessage;
    private javax.swing.JTextArea jMs;
    private javax.swing.JPanel jP;
    private javax.swing.JTextField jParticipant;
    private javax.swing.JList<String> jPs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jSend;
    private javax.swing.JButton jSendF;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    /**
     * Update messages box
     * @param newMessage      
     */
    protected void updateMessages(String newMessage) {
        this.jMs.append(newMessage);
    }
    
    protected void updateParticipants(List<String> participants){
        setJList(jPs, participants);
    }
    
    @Override
    public void dispose(){
        MainW w = (MainW) parent;
        w.removeChild(this.conversationId);
        super.dispose();
    }
    
    
    /**
     * Initialize the conversation when the user opens the conversation window.
     */
    protected void initConversation(String content){
        this.jMs.setText(content);
    }

}
