package gui;

import cmd.obj.Conversation;
import cmd.obj.Message;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

public class MainW extends Window {

    private List<Conversation> conversations;   //list of the conversations DETAILS
    /** OPENED conversation windows
     * <db_conv_id,conversation_object>
     */
    private Map<Integer, ConversationW> cws; 

    public MainW(Window parent) {
        super(parent);
        initComponents();
        cws = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jC = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCs = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jNewC = new javax.swing.JButton();
        jOpenC = new javax.swing.JButton();
        jCName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jF = new javax.swing.JPanel();
        jAddF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jFs = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(jCs);

        jLabel2.setText("Conversations");

        jNewC.setText("New conversation");
        jNewC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewCActionPerformed(evt);
            }
        });

        jOpenC.setText("Open conversation");
        jOpenC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenCActionPerformed(evt);
            }
        });

        jLabel3.setText("Conversation Name");

        javax.swing.GroupLayout jCLayout = new javax.swing.GroupLayout(jC);
        jC.setLayout(jCLayout);
        jCLayout.setHorizontalGroup(
            jCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jNewC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jOpenC, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jCName)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jCLayout.setVerticalGroup(
            jCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCLayout.createSequentialGroup()
                        .addComponent(jCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNewC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOpenC)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addContainerGap())
        );

        jAddF.setText("Add friend");

        jScrollPane1.setViewportView(jFs);

        jLabel1.setText("Friends");

        javax.swing.GroupLayout jFLayout = new javax.swing.GroupLayout(jF);
        jF.setLayout(jFLayout);
        jFLayout.setHorizontalGroup(
            jFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFLayout.setVerticalGroup(
            jFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jFLayout.createSequentialGroup()
                        .addComponent(jAddF)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNewCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewCActionPerformed
        try {
            String convName = jCName.getText();
            if (convName != null && convName.length() != 0) {
                c.createConversation(convName);
            }
        } catch (IOException ex) {
            Logger.getLogger(MainW.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jNewCActionPerformed

    private void jOpenCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenCActionPerformed
        int[] selected = jCs.getSelectedIndices();
        for (int i : selected) {
            Conversation c = this.conversations.get(i);
            ConversationW w = new ConversationW(this, c);
            int convId = c.getConversationId();
            cws.put(convId, w);
            addChild(w);
            w.setVisible(true);
            w.setTitle("YChat - Conversation: " + c.getName());
            w.updateParticipants(new ArrayList<String>());
            Window.c.updateParticipants(convId, new ArrayList<>());
            Window.c.getMessages(convId);
        }
    }//GEN-LAST:event_jOpenCActionPerformed

    public void updateConversations(List<Conversation> cl) {
        this.conversations = cl;

        String[] listData = cl.stream().map((x) -> x.getName()).toArray(String[]::new); //list of the names of the conversations
        //Map conversations = cl.stream().collect(Collectors.toMap(x->x.getConversationId(), Conversation::getName));        
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String i : listData) {
            model.addElement(i);
        }
        jCs.setModel(model);
    }
    
    
    public void updateMessages(int conversationId, String newMessage) {
        if (cws.containsKey(conversationId))
            cws.get(conversationId).updateMessages(newMessage);
    }
    
    
    /**
     * Send message to the client root to send it to the server.
     * @param conversationId
     * @param msg
     * @throws IOException 
     */
    public void sendMessage(int conversationId, Message msg) throws IOException{
        this.c.sendMessage(conversationId, msg);
    }
    
    
    /**
     * Update the participants from the client conversation windows
     * @param conversationId
     * @param participants
     * @throws IOException 
     */
    public void updateParticipants(int conversationId, List<String> participants) throws IOException{
        if (cws.containsKey(conversationId))
            cws.get(conversationId).updateParticipants(participants);
    }
    
    /**
     * Add participants to the conversation, by sending them to the server.
     * @param conversationId
     * @param participants
     * @throws IOException 
     */
    public void addParticipants(int conversationId, List<String> participants) throws IOException{
        Window.c.updateParticipants(conversationId, participants);
    }
    
    protected void removeChild(int childId){
        this.cws.remove(childId);
    }
    
    /**
     * Update the messages from the conversations.
     * @param convId
     * @param messages 
     */
    public void receiveMessages(int convId, List<Message> messages){
        //write the messages as a string
        String msgs = "";
        for (Message m : messages){
            msgs += m.getOwner()+": "+m.getContent()+"\n";
        }
        if (cws.containsKey(convId))
            cws.get(convId).initConversation(msgs);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddF;
    private javax.swing.JPanel jC;
    private javax.swing.JTextField jCName;
    private javax.swing.JList<String> jCs;
    private javax.swing.JPanel jF;
    private javax.swing.JList<String> jFs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jNewC;
    private javax.swing.JButton jOpenC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
