package gui;

import client.Client;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;

public abstract class Window extends javax.swing.JFrame {
    protected static Client c;
    protected final Window parent;
    protected final List<Window> children;
    
    public Window(Window parent) {
        this.parent = parent;
        this.children = new ArrayList<>();
        initComponents();
    }
    

    public static void setClient(Client client){
        Window.c = client;
    }
    
    public void addChild(Window cw){
        this.children.add(cw);
    }
    
    public void setList(List<String> myList, JList<String> jList){
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String i : myList) {
            model.addElement(i);
        }
        jList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
